baseurl = "https://www.hvitfeldt.me/"
title = "Emil Hvitfeldt"
theme = "hugo-creative-portfolio-theme"
twitterAuthor = "@Emil_Hvitfeldt"
enableEmoji = true
languageCode = "en-us"
pluralizeListTitles = false
# Enable comments by entering your Disqus shortname
disqusShortname = "https-emilhvitfeldt-github-io"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-98238582-1"

[permalinks]
  post = "/:year/:month/:slug/"

  ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "My R adventures."
  copyright = "&copy;2019 Emil Hvitfeldt @Emil_Hvitfeldt"
  sidebarAbout = [
    "I love to develop and make things in R. Working on visualization styles, modeling techniques and general workflow problems."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "emilhhvitfeldt@gmail.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Blog"
  url = "blog/"
  home = true
  
  [[params.navlinks]]
  name = "GenArt"
  url = "GenArt/"

  [[params.navlinks]]
  name = "About"
  url = "about/"
  
  [[params.navlinks]]
  name = "ERAN"
  url = "src/contrib/"

  [params.social]
  email        = "emilhhvitfeldt@gmail.com"
  twitter      = "https://twitter.com/Emil_Hvitfeldt"
  linkedin     = "https://www.linkedin.com/in/emilhvitfeldt/"
  github       = "https://github.com/EmilHvitfeldt"

    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "python", "sql"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"