library(craneur)
emil <- Craneur$new("Emil")
emil$add_package("../cookiemonster_0.1.0.tar.gz")
emil$add_package("../ehlib_0.2.7.tar.gz")
emil$add_package("../ggpage_0.2.2.tar.gz")
emil$add_package("../ggtetris_0.1.0.tar.gz")
emil$add_package("../hcandersenr_0.1.3.tar.gz")
emil$add_package("../offensiveR_0.1.3.tar.gz")
emil$add_package("../paletteer_0.1.0.9000.tar.gz")
emil$add_package("../quickpalette_0.1.2.tar.gz")
emil$add_package("../tilemapr_0.1.001.tar.gz")
emil$add_package("../walmartAPI_0.1.5.9000.tar.gz")
emil

emil$write(path = "./content")
