---
title: "2019 Package Calendar"
author: "Emil Hvitfeldt"
output: 
  html_document:
    css: "calendar.css"
showonlyimage: false
description: " "
type: packagecalendar
layout:: single
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = FALSE)
library(htmltools)
```

```{r}
tags$section(class = "navigation",
  tags$div(class = "nav-container",
    tags$nav(
      tags$ul(class = "nav-list",
        tags$li(
          tags$a(href = "https://www.hvitfeldt.me/", "Home")
        )
      )
    )
  )
)
```

# 2019 Package Calendar

```{r}
library(shinyparticles)
library(magrittr)

particles_config(particles.number.value = 100, particles.color.value = "#FFF", particles.opacity.random = TRUE, particles.size.value = 10, particles.line_linked.enable = FALSE, particles.move.direction = "bottom", particles.move.speed = 1, interactivity.events.onclick.enable = FALSE, interactivity.events.onhover.enable = FALSE) %>% 
  particles()
```

```{r, echo = FALSE}
cross_stitch <- function(background, color1, color2, width1 = 20, width2 = 20) {
  glue::glue("
  background-color: {background};
  background-image:
	repeating-linear-gradient(
		-45deg,
		transparent,
		transparent {width1}px,
		{color1} 0,
		{color1} 40px
	),
	repeating-linear-gradient(
		45deg,
		transparent,
		transparent {width2}px,
		{color2} 0,
		{color2} 40px
	);
  background-blend-mode: multiply;
            ") 
}
```

```{r}

```


```{r, echo=FALSE}
make_package <- function(x) {
  random_green <- sample(c("#004000",
"#004800",
"#005000",
"#005800",
"#006000",
"#006800",
"#007000",
"#007800",
"#008000",
"#008800"), 1)
  
  div(class = "item",
      "hello",
      style = paste("width: 200px; height: 200px;", 
                    cross_stitch("white", random_green, "crimson", 30, 30))
  ) 
}
```

```{r, echo=FALSE}
div(class = "items",
  purrr::map(1:24, ~ make_package(.x))
)
```

